import { Injectable } from "../../../node_modules/@angular/core";

export interface Country {
    Name: string;
    Code: string;
    ISO: string;
}

@Injectable()
export class CountryCallCodesService {

  constructor() { }

  getCountryList() {
    return this.countryList;
  }

   private countryList: Country[] = [
      {Name: "Afghanistan", ISO: "AF", Code: "+93"},
      {Name: "Albania", ISO: "AL", Code: "+355"},
      {Name: "Algeria", ISO: "DZ", Code: "+213"},
      {Name: "American Samoa", ISO: "AS", Code: "+1"},
      {Name: "Andorra", ISO: "AD", Code: "+376"},
      {Name: "Angola", ISO: "AO", Code: "+244"},
      {Name: "Anguilla", ISO: "AI", Code: "+1"},
      {Name: "Antigua and Barbuda", ISO: "AG", Code: "+1"},
      {Name: "Argentina", ISO: "AR", Code: "+54"},
      {Name: "Armenia", ISO: "AM", Code: "+374"},
      {Name: "Aruba", ISO: "AW", Code: "+297"},
      {Name: "Australia", ISO: "AU", Code: "+61"},
      {Name: "Austria", ISO: "AT", Code: "+43"},
      {Name: "Azerbaijan", ISO: "AZ", Code: "+994"},
      {Name: "Bahamas", ISO: "BS", Code: "+1"},
      {Name: "Bahrain", ISO: "BH", Code: "+973"},
      {Name: "Bangladesh", ISO: "BD", Code: "+880"},
      {Name: "Barbados", ISO: "BB", Code: "+1"},
      {Name: "Belarus", ISO: "BY", Code: "+375"},
      {Name: "Belgium", ISO: "BE", Code: "+32"},
      {Name: "Belize", ISO: "BZ", Code: "+501"},
      {Name: "Benin", ISO: "BJ", Code: "+229"},
      {Name: "Bermuda", ISO: "BM", Code: "+1"},
      {Name: "Bhutan", ISO: "BT", Code: "+975"},
      {Name: "Bolivia", ISO: "BO", Code: "+591"},
      {Name: "Bosnia and Herzegovina", ISO: "BA", Code: "+387"},
      {Name: "Botswana", ISO: "BW", Code: "+267"},
      {Name: "Brazil", ISO: "BR", Code: "+55"},
      {Name: "British Indian Ocean Territory", ISO: "IO", Code: "+246"},
      {Name: "British Virgin Islands", ISO: "VG", Code: "+1"},
      {Name: "Brunei", ISO: "BN", Code: "+673"},
      {Name: "Bulgaria", ISO: "BG", Code: "+359"},
      {Name: "Burkina Faso", ISO: "BF", Code: "+226"},
      {Name: "Burundi", ISO: "BI", Code: "+257"},
      {Name: "Cambodia", ISO: "KH", Code: "+855"},
      {Name: "Cameroon", ISO: "CM", Code: "+237"},
      {Name: "Canada", ISO: "CA", Code: "+1"},
      {Name: "Cape Verde", ISO: "CV", Code: "+238"},
      {Name: "Caribbean Netherlands", ISO: "BQ", Code: "+599"},
      {Name: "Cayman Islands", ISO: "KY", Code: "+1"},
      {Name: "Central African Republic", ISO: "CF", Code: "+236"},
      {Name: "Chad", ISO: "TD", Code: "+235"},
      {Name: "Chile", ISO: "CL", Code: "+56"},
      {Name: "China", ISO: "CN", Code: "+86"},
      {Name: "Colombia", ISO: "CO", Code: "+57"},
      {Name: "Comoros", ISO: "KM", Code: "+269"},
      {Name: "Congo (DRC)", ISO: "CD", Code: "+243"},
      {Name: "Congo (Republic)", ISO: "CG", Code: "+242"},
      {Name: "Cook Islands", ISO: "CK", Code: "+682"},
      {Name: "Costa Rica", ISO: "CR", Code: "+506"},
      {Name: "CÃ´te dâ€™Ivoire", ISO: "CI", Code: "+225"},
      {Name: "Croatia", ISO: "HR", Code: "+385"},
      {Name: "Cuba", ISO: "CU", Code: "+53"},
      {Name: "CuraÃ§ao", ISO: "CW", Code: "+599"},
      {Name: "Cyprus", ISO: "CY", Code: "+357"},
      {Name: "Czech Republic", ISO: "CZ", Code: "+420"},
      {Name: "Denmark", ISO: "DK", Code: "+45"},
      {Name: "Djibouti", ISO: "DJ", Code: "+253"},
      {Name: "Dominica", ISO: "DM", Code: "+1"},
      {Name: "Dominican Republic", ISO: "DO", Code: "+1"},
      {Name: "Ecuador", ISO: "EC", Code: "+593"},
      {Name: "Egypt", ISO: "EG", Code: "+20"},
      {Name: "El Salvador", ISO: "SV", Code: "+503"},
      {Name: "Equatorial Guinea", ISO: "GQ", Code: "+240"},
      {Name: "Eritrea", ISO: "ER", Code: "+291"},
      {Name: "Estonia", ISO: "EE", Code: "+372"},
      {Name: "Ethiopia", ISO: "ET", Code: "+251"},
      {Name: "Falkland Islands", ISO: "FK", Code: "+500"},
      {Name: "Faroe Islands", ISO: "FO", Code: "+298"},
      {Name: "Fiji", ISO: "FJ", Code: "+679"},
      {Name: "Finland", ISO: "FI", Code: "+358"},
      {Name: "France", ISO: "FR", Code: "+33"},
      {Name: "French Guiana", ISO: "GF", Code: "+594"},
      {Name: "French Polynesia", ISO: "PF", Code: "+689"},
      {Name: "Gabon", ISO: "GA", Code: "+241"},
      {Name: "Gambia", ISO: "GM", Code: "+220"},
      {Name: "Georgia", ISO: "GE", Code: "+995"},
      {Name: "Germany", ISO: "DE", Code: "+49"},
      {Name: "Ghana", ISO: "GH", Code: "+233"},
      {Name: "Gibraltar", ISO: "GI", Code: "+350"},
      {Name: "Greece", ISO: "GR", Code: "+30"},
      {Name: "Greenland", ISO: "GL", Code: "+299"},
      {Name: "Grenada", ISO: "GD", Code: "+1"},
      {Name: "Guadeloupe", ISO: "GP", Code: "+590"},
      {Name: "Guam", ISO: "GU", Code: "+1"},
      {Name: "Guatemala", ISO: "GT", Code: "+502"},
      {Name: "Guinea", ISO: "GN", Code: "+224"},
      {Name: "Guinea-Bissau", ISO: "GW", Code: "+245"},
      {Name: "Guyana", ISO: "GY", Code: "+592"},
      {Name: "Haiti", ISO: "HT", Code: "+509"},
      {Name: "Honduras", ISO: "HN", Code: "+504"},
      {Name: "Hong Kong", ISO: "HK", Code: "+852"},
      {Name: "Hungary", ISO: "HU", Code: "+36"},
      {Name: "Iceland", ISO: "IS", Code: "+354"},
      {Name: "India", ISO: "IN", Code: "+91"},
      {Name: "Indonesia", ISO: "ID", Code: "+62"},
      {Name: "Iran", ISO: "IR", Code: "+98"},
      {Name: "Iraq", ISO: "IQ", Code: "+964"},
      {Name: "Ireland", ISO: "IE", Code: "+353"},
      {Name: "Israel", ISO: "IL", Code: "+972"},
      {Name: "Italy", ISO: "IT", Code: "+39"},
      {Name: "Jamaica", ISO: "JM", Code: "+1"},
      {Name: "Japan", ISO: "JP", Code: "+81"},
      {Name: "Jordan", ISO: "JO", Code: "+962"},
      {Name: "Kazakhstan", ISO: "KZ", Code: "+7"},
      {Name: "Kenya", ISO: "KE", Code: "+254"},
      {Name: "Kiribati", ISO: "KI", Code: "+686"},
      {Name: "Kuwait", ISO: "KW", Code: "+965"},
      {Name: "Kyrgyzstan", ISO: "KG", Code: "+996"},
      {Name: "Laos", ISO: "LA", Code: "+856"},
      {Name: "Latvia", ISO: "LV", Code: "+371"},
      {Name: "Lebanon", ISO: "LB", Code: "+961"},
      {Name: "Lesotho", ISO: "LS", Code: "+266"},
      {Name: "Liberia", ISO: "LR", Code: "+231"},
      {Name: "Libya", ISO: "LY", Code: "+218"},
      {Name: "Liechtenstein", ISO: "LI", Code: "+423"},
      {Name: "Lithuania", ISO: "LT", Code: "+370"},
      {Name: "Luxembourg", ISO: "LU", Code: "+352"},
      {Name: "Macau", ISO: "MO", Code: "+853"},
      {Name: "Macedonia", ISO: "MK", Code: "+389"},
      {Name: "Madagascar", ISO: "MG", Code: "+261"},
      {Name: "Malawi", ISO: "MW", Code: "+265"},
      {Name: "Malaysia", ISO: "MY", Code: "+60"},
      {Name: "Maldives", ISO: "MV", Code: "+960"},
      {Name: "Mali", ISO: "ML", Code: "+223"},
      {Name: "Malta", ISO: "MT", Code: "+356"},
      {Name: "Marshall Islands", ISO: "MH", Code: "+692"},
      {Name: "Martinique", ISO: "MQ", Code: "+596"},
      {Name: "Mauritania", ISO: "MR", Code: "+222"},
      {Name: "Mauritius", ISO: "MU", Code: "+230"},
      {Name: "Mexico", ISO: "MX", Code: "+52"},
      {Name: "Micronesia", ISO: "FM", Code: "+691"},
      {Name: "Moldova", ISO: "MD", Code: "+373"},
      {Name: "Monaco", ISO: "MC", Code: "+377"},
      {Name: "Mongolia", ISO: "MN", Code: "+976"},
      {Name: "Montenegro", ISO: "ME", Code: "+382"},
      {Name: "Montserrat", ISO: "MS", Code: "+1"},
      {Name: "Morocco", ISO: "MA", Code: "+212"},
      {Name: "Mozambique", ISO: "MZ", Code: "+258"},
      {Name: "Myanmar", ISO: "MM", Code: "+95"},
      {Name: "Namibia", ISO: "NA", Code: "+264"},
      {Name: "Nauru", ISO: "NR", Code: "+674"},
      {Name: "Nepal", ISO: "NP", Code: "+977"},
      {Name: "Netherlands", ISO: "NL", Code: "+31"},
      {Name: "New Caledonia", ISO: "NC", Code: "+687"},
      {Name: "New Zealand", ISO: "NZ", Code: "+64"},
      {Name: "Nicaragua", ISO: "NI", Code: "+505"},
      {Name: "Niger", ISO: "NE", Code: "+227"},
      {Name: "Nigeria", ISO: "NG", Code: "+234"},
      {Name: "Niue", ISO: "NU", Code: "+683"},
      {Name: "Norfolk Island", ISO: "NF", Code: "+672"},
      {Name: "North Korea", ISO: "KP", Code: "+850"},
      {Name: "Northern Mariana Islands", ISO: "MP", Code: "+1"},
      {Name: "Norway", ISO: "NO", Code: "+47"},
      {Name: "Oman", ISO: "OM", Code: "+968"},
      {Name: "Pakistan", ISO: "PK", Code: "+92"},
      {Name: "Palau", ISO: "PW", Code: "+680"},
      {Name: "Palestine", ISO: "PS", Code: "+970"},
      {Name: "Panama", ISO: "PA", Code: "+507"},
      {Name: "Papua New Guinea", ISO: "PG", Code: "+675"},
      {Name: "Paraguay", ISO: "PY", Code: "+595"},
      {Name: "Peru", ISO: "PE", Code: "+51"},
      {Name: "Philippines", ISO: "PH", Code: "+63"},
      {Name: "Poland", ISO: "PL", Code: "+48"},
      {Name: "Portugal", ISO: "PT", Code: "+351"},
      {Name: "Puerto Rico", ISO: "PR", Code: "+1"},
      {Name: "Qatar", ISO: "QA", Code: "+974"},
      {Name: "RÃ©union", ISO: "RE", Code: "+262"},
      {Name: "Romania", ISO: "RO", Code: "+40"},
      {Name: "Russia", ISO: "RU", Code: "+7"},
      {Name: "Rwanda", ISO: "RW", Code: "+250"},
      {Name: "Saint BarthÃ©lemy", ISO: "BL", Code: "+590"},
      {Name: "Saint Helena", ISO: "SH", Code: "+290"},
      {Name: "Saint Kitts and Nevis", ISO: "KN", Code: "+1"},
      {Name: "Saint Lucia", ISO: "LC", Code: "+1"},
      {Name: "Saint Martin", ISO: "MF", Code: "+590"},
      {Name: "Saint Pierre and Miquelon", ISO: "PM", Code: "+508"},
      {Name: "Saint Vincent and the Grenadines", ISO: "VC", Code: "+1"},
      {Name: "Samoa", ISO: "WS", Code: "+685"},
      {Name: "San Marino", ISO: "SM", Code: "+378"},
      {Name: "SÃ£o TomÃ© and PrÃ­ncipe", ISO: "ST", Code: "+239"},
      {Name: "Saudi Arabia", ISO: "SA", Code: "+966"},
      {Name: "Senegal", ISO: "SN", Code: "+221"},
      {Name: "Serbia", ISO: "RS", Code: "+381"},
      {Name: "Seychelles", ISO: "SC", Code: "+248"},
      {Name: "Sierra Leone", ISO: "SL", Code: "+232"},
      {Name: "Singapore", ISO: "SG", Code: "+65"},
      {Name: "Sint Maarten", ISO: "SX", Code: "+1"},
      {Name: "Slovakia", ISO: "SK", Code: "+421"},
      {Name: "Slovenia", ISO: "SI", Code: "+386"},
      {Name: "Solomon Islands", ISO: "SB", Code: "+677"},
      {Name: "Somalia", ISO: "SO", Code: "+252"},
      {Name: "South Africa", ISO: "ZA", Code: "+27"},
      {Name: "South Korea", ISO: "KR", Code: "+82"},
      {Name: "South Sudan", ISO: "SS", Code: "+211"},
      {Name: "Spain", ISO: "ES", Code: "+34"},
      {Name: "Sri Lanka", ISO: "LK", Code: "+94"},
      {Name: "Sudan", ISO: "SD", Code: "+249"},
      {Name: "Suriname", ISO: "SR", Code: "+597"},
      {Name: "Swaziland", ISO: "SZ", Code: "+268"},
      {Name: "Sweden", ISO: "SE", Code: "+46"},
      {Name: "Switzerland", ISO: "CH", Code: "+41"},
      {Name: "Syria", ISO: "SY", Code: "+963"},
      {Name: "Taiwan", ISO: "TW", Code: "+886"},
      {Name: "Tajikistan", ISO: "TJ", Code: "+992"},
      {Name: "Tanzania", ISO: "TZ", Code: "+255"},
      {Name: "Thailand", ISO: "TH", Code: "+66"},
      {Name: "Timor-Leste", ISO: "TL", Code: "+670"},
      {Name: "Togo", ISO: "TG", Code: "+228"},
      {Name: "Tokelau", ISO: "TK", Code: "+690"},
      {Name: "Tonga", ISO: "TO", Code: "+676"},
      {Name: "Trinidad and Tobago", ISO: "TT", Code: "+1"},
      {Name: "Tunisia", ISO: "TN", Code: "+216"},
      {Name: "Turkey", ISO: "TR", Code: "+90"},
      {Name: "Turkmenistan", ISO: "TM", Code: "+993"},
      {Name: "Turks and Caicos Islands", ISO: "TC", Code: "+1"},
      {Name: "Tuvalu", ISO: "TV", Code: "+688"},
      {Name: "U.S. Virgin Islands", ISO: "VI", Code: "+1"},
      {Name: "Uganda", ISO: "UG", Code: "+256"},
      {Name: "Ukraine", ISO: "UA", Code: "+380"},
      {Name: "United Arab Emirates", ISO: "AE", Code: "+971"},
      {Name: "United Kingdom", ISO: "GB", Code: "+44"},
      {Name: "United States", ISO: "US", Code: "+1"},
      {Name: "Uruguay", ISO: "UY", Code: "+598"},
      {Name: "Uzbekistan", ISO: "UZ", Code: "+998"},
      {Name: "Vanuatu", ISO: "VU", Code: "+678"},
      {Name: "Vatican City", ISO: "VA", Code: "+39"},
      {Name: "Venezuela", ISO: "VE", Code: "+58"},
      {Name: "Vietnam", ISO: "VN", Code: "+84"},
      {Name: "Wallis and Futuna", ISO: "WF", Code: "+681"},
      {Name: "Yemen", ISO: "YE", Code: "+967"},
      {Name: "Zambia", ISO: "ZM", Code: "+260"},
      {Name: "Zimbabwe", ISO: "ZW", Code: "+263"} 
   ]
  }